# Change the leader key from Ctrl+b to Ctrl+a
# Im a GNU Screen child
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Ensure window index number get reordered on delete.
set-option -g renumber-windows on

# Window numbering starts at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# For Tmux to not fuck the colors up
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
